import { useUser } from "@clerk/nextjs";
import { type ReactNode } from "react";
import Head from "next/head";
import Footer from "./Footer";
import Header from "./Header";
import Spinner from "../Spinner";

const Layout = ({ children }: { children: ReactNode }) => {
  const { isLoaded: userLoaded } = useUser();

  if (!userLoaded) return <Spinner tw="min-h-screen" />;

  return (
    <>
      <Head>
        <title>Mojify</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid min-h-screen grid-rows-[auto_1fr_auto]">
        <Header />
        {children}
        <Footer />
      </main>
    </>
  );
};
export default Layout;
