import { type ReactNode } from "react";
import Head from "next/head";
import { Toaster } from "react-hot-toast";
import Footer from "./Footer";
import Header from "./Header";

const Layout = ({ children }: { children: ReactNode }) => {
  return (
    <>
      <Head>
        <title>Mojify</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className="grid min-h-screen grid-rows-[auto_1fr_auto]">
        <Header />
        <main className="mx-auto flex w-full max-w-lg flex-col items-center gap-14 px-4">
          {children}
        </main>
        <Footer />
        <Toaster position="bottom-center" />
      </main>
    </>
  );
};
export default Layout;
