import { type NextPage } from "next";
import Head from "next/head";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import PostForm from "~/components/PostForm";
import TweetView from "~/components/TweetView";

import { api } from "~/utils/api";

// dayjs cofig
dayjs.extend(relativeTime);

const Home: NextPage = () => {
  const { data } = api.posts.getAll.useQuery();
  return (
    <>
      <Head>
        <title>Mojify</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto flex w-full max-w-lg flex-col items-center gap-14">
        <PostForm />
        <ul className="flex w-full flex-col gap-4">
          {data?.map(({ post, author }) => (
            <TweetView key={post.id} post={post} author={author} />
          ))}
        </ul>
      </main>
    </>
  );
};

export default Home;
